import os
from dotenv import load_dotenv

load_dotenv()

CTRADER_CLIENT_ID = os.getenv("CTRADER_CLIENT_ID", "")
CTRADER_CLIENT_SECRET = os.getenv("CTRADER_CLIENT_SECRET", "")
CTRADER_ACCESS_TOKEN = os.getenv("CTRADER_ACCESS_TOKEN", "")
CTRADER_REFRESH_TOKEN = os.getenv("CTRADER_REFRESH_TOKEN", "")
CTRADER_ACCOUNT_ID = int(os.getenv("CTRADER_ACCOUNT_ID", "0"))

SYMBOL_NAME = os.getenv("SYMBOL_NAME", "XAUUSD")
TRADE_VOLUME = float(os.getenv("TRADE_VOLUME", "0.01"))
MAX_LOSS_PERCENT = float(os.getenv("MAX_LOSS_PERCENT", "1.0"))
LEVERAGE = 20
STOP_LOSS_PIPS = 200
TAKE_PROFIT_PIPS = 400
MIN_INTERVAL_MINUTES = 60
ADX_THRESHOLD = 25
ATR_PERIOD = 14
EMA_PERIOD = 20
